services:
  - type: web
    name: AI-Powered-Sustainable-Packaging-Recommendation-System
    env: python
    buildCommand: python -m pip install --upgrade pip && pip install -r requirements.txt --prefer-binary
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.2
